global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "gateway"
    static_configs: [{ targets: ["gateway:8000"] }]
  - job_name: "auth"
    static_configs: [{ targets: ["auth-service:8001"] }]
  - job_name: "product"
    static_configs: [{ targets: ["product-service:8002"] }]
  - job_name: "order"
    static_configs: [{ targets: ["order-service:8003"] }]
  - job_name: "payment"
    static_configs: [{ targets: ["payment-service:8004"] }]
  - job_name: "notification"
    static_configs: [{ targets: ["notification-service:8005"] }]
