name: CD
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH (EC2)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ec2-user
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /opt/university-marketplace
            git pull
            docker compose up -d --build
